/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace DPP {
  export type PassportStruct = {
    batchId: string;
    product: string;
    origin: string;
    active: boolean;
    createdAt: BigNumberish;
  };

  export type PassportStructOutput = [
    batchId: string,
    product: string,
    origin: string,
    active: boolean,
    createdAt: bigint
  ] & {
    batchId: string;
    product: string;
    origin: string;
    active: boolean;
    createdAt: bigint;
  };
}

export interface DPPInterface extends Interface {
  getFunction(
    nameOrSignature: "createPassport" | "getPassport" | "setPassportStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PassportCreated" | "PassportStatusUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createPassport",
    values: [BytesLike, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPassport",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPassportStatus",
    values: [BytesLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "createPassport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPassport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPassportStatus",
    data: BytesLike
  ): Result;
}

export namespace PassportCreatedEvent {
  export type InputTuple = [
    passportId: BytesLike,
    batchId: string,
    product: string,
    origin: string
  ];
  export type OutputTuple = [
    passportId: string,
    batchId: string,
    product: string,
    origin: string
  ];
  export interface OutputObject {
    passportId: string;
    batchId: string;
    product: string;
    origin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PassportStatusUpdatedEvent {
  export type InputTuple = [passportId: BytesLike, active: boolean];
  export type OutputTuple = [passportId: string, active: boolean];
  export interface OutputObject {
    passportId: string;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DPP extends BaseContract {
  connect(runner?: ContractRunner | null): DPP;
  waitForDeployment(): Promise<this>;

  interface: DPPInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createPassport: TypedContractMethod<
    [passportId: BytesLike, batchId: string, product: string, origin: string],
    [void],
    "nonpayable"
  >;

  getPassport: TypedContractMethod<
    [passportId: BytesLike],
    [DPP.PassportStructOutput],
    "view"
  >;

  setPassportStatus: TypedContractMethod<
    [passportId: BytesLike, active: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createPassport"
  ): TypedContractMethod<
    [passportId: BytesLike, batchId: string, product: string, origin: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPassport"
  ): TypedContractMethod<
    [passportId: BytesLike],
    [DPP.PassportStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "setPassportStatus"
  ): TypedContractMethod<
    [passportId: BytesLike, active: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PassportCreated"
  ): TypedContractEvent<
    PassportCreatedEvent.InputTuple,
    PassportCreatedEvent.OutputTuple,
    PassportCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PassportStatusUpdated"
  ): TypedContractEvent<
    PassportStatusUpdatedEvent.InputTuple,
    PassportStatusUpdatedEvent.OutputTuple,
    PassportStatusUpdatedEvent.OutputObject
  >;

  filters: {
    "PassportCreated(bytes32,string,string,string)": TypedContractEvent<
      PassportCreatedEvent.InputTuple,
      PassportCreatedEvent.OutputTuple,
      PassportCreatedEvent.OutputObject
    >;
    PassportCreated: TypedContractEvent<
      PassportCreatedEvent.InputTuple,
      PassportCreatedEvent.OutputTuple,
      PassportCreatedEvent.OutputObject
    >;

    "PassportStatusUpdated(bytes32,bool)": TypedContractEvent<
      PassportStatusUpdatedEvent.InputTuple,
      PassportStatusUpdatedEvent.OutputTuple,
      PassportStatusUpdatedEvent.OutputObject
    >;
    PassportStatusUpdated: TypedContractEvent<
      PassportStatusUpdatedEvent.InputTuple,
      PassportStatusUpdatedEvent.OutputTuple,
      PassportStatusUpdatedEvent.OutputObject
    >;
  };
}
