/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOffer"
      | "cancelListing"
      | "createListing"
      | "listings"
      | "offers"
      | "placeOffer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ListingCancelled"
      | "ListingCreated"
      | "OfferAccepted"
      | "OfferPlaced"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOffer",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelListing",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createListing",
    values: [BytesLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "listings", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "offers", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "placeOffer",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "offers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeOffer", data: BytesLike): Result;
}

export namespace ListingCancelledEvent {
  export type InputTuple = [listingId: BytesLike];
  export type OutputTuple = [listingId: string];
  export interface OutputObject {
    listingId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListingCreatedEvent {
  export type InputTuple = [
    listingId: BytesLike,
    seller: AddressLike,
    passportId: BytesLike,
    unitPrice: BigNumberish,
    quantity: BigNumberish
  ];
  export type OutputTuple = [
    listingId: string,
    seller: string,
    passportId: string,
    unitPrice: bigint,
    quantity: bigint
  ];
  export interface OutputObject {
    listingId: string;
    seller: string;
    passportId: string;
    unitPrice: bigint;
    quantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferAcceptedEvent {
  export type InputTuple = [
    offerId: BytesLike,
    listingId: BytesLike,
    seller: AddressLike,
    buyer: AddressLike,
    totalPrice: BigNumberish
  ];
  export type OutputTuple = [
    offerId: string,
    listingId: string,
    seller: string,
    buyer: string,
    totalPrice: bigint
  ];
  export interface OutputObject {
    offerId: string;
    listingId: string;
    seller: string;
    buyer: string;
    totalPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferPlacedEvent {
  export type InputTuple = [
    offerId: BytesLike,
    listingId: BytesLike,
    buyer: AddressLike,
    quantity: BigNumberish,
    totalPrice: BigNumberish
  ];
  export type OutputTuple = [
    offerId: string,
    listingId: string,
    buyer: string,
    quantity: bigint,
    totalPrice: bigint
  ];
  export interface OutputObject {
    offerId: string;
    listingId: string;
    buyer: string;
    quantity: bigint;
    totalPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Marketplace extends BaseContract {
  connect(runner?: ContractRunner | null): Marketplace;
  waitForDeployment(): Promise<this>;

  interface: MarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOffer: TypedContractMethod<[offerId: BytesLike], [void], "nonpayable">;

  cancelListing: TypedContractMethod<
    [listingId: BytesLike],
    [void],
    "nonpayable"
  >;

  createListing: TypedContractMethod<
    [
      listingId: BytesLike,
      passportId: BytesLike,
      unitPrice: BigNumberish,
      quantity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  listings: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        seller: string;
        passportId: string;
        unitPrice: bigint;
        totalQuantity: bigint;
        availableQuantity: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  offers: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint] & {
        buyer: string;
        listingId: string;
        quantity: bigint;
        totalPrice: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  placeOffer: TypedContractMethod<
    [offerId: BytesLike, listingId: BytesLike, quantity: BigNumberish],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOffer"
  ): TypedContractMethod<[offerId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelListing"
  ): TypedContractMethod<[listingId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createListing"
  ): TypedContractMethod<
    [
      listingId: BytesLike,
      passportId: BytesLike,
      unitPrice: BigNumberish,
      quantity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        seller: string;
        passportId: string;
        unitPrice: bigint;
        totalQuantity: bigint;
        availableQuantity: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "offers"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint] & {
        buyer: string;
        listingId: string;
        quantity: bigint;
        totalPrice: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "placeOffer"
  ): TypedContractMethod<
    [offerId: BytesLike, listingId: BytesLike, quantity: BigNumberish],
    [void],
    "payable"
  >;

  getEvent(
    key: "ListingCancelled"
  ): TypedContractEvent<
    ListingCancelledEvent.InputTuple,
    ListingCancelledEvent.OutputTuple,
    ListingCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ListingCreated"
  ): TypedContractEvent<
    ListingCreatedEvent.InputTuple,
    ListingCreatedEvent.OutputTuple,
    ListingCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OfferAccepted"
  ): TypedContractEvent<
    OfferAcceptedEvent.InputTuple,
    OfferAcceptedEvent.OutputTuple,
    OfferAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "OfferPlaced"
  ): TypedContractEvent<
    OfferPlacedEvent.InputTuple,
    OfferPlacedEvent.OutputTuple,
    OfferPlacedEvent.OutputObject
  >;

  filters: {
    "ListingCancelled(bytes32)": TypedContractEvent<
      ListingCancelledEvent.InputTuple,
      ListingCancelledEvent.OutputTuple,
      ListingCancelledEvent.OutputObject
    >;
    ListingCancelled: TypedContractEvent<
      ListingCancelledEvent.InputTuple,
      ListingCancelledEvent.OutputTuple,
      ListingCancelledEvent.OutputObject
    >;

    "ListingCreated(bytes32,address,bytes32,uint256,uint256)": TypedContractEvent<
      ListingCreatedEvent.InputTuple,
      ListingCreatedEvent.OutputTuple,
      ListingCreatedEvent.OutputObject
    >;
    ListingCreated: TypedContractEvent<
      ListingCreatedEvent.InputTuple,
      ListingCreatedEvent.OutputTuple,
      ListingCreatedEvent.OutputObject
    >;

    "OfferAccepted(bytes32,bytes32,address,address,uint256)": TypedContractEvent<
      OfferAcceptedEvent.InputTuple,
      OfferAcceptedEvent.OutputTuple,
      OfferAcceptedEvent.OutputObject
    >;
    OfferAccepted: TypedContractEvent<
      OfferAcceptedEvent.InputTuple,
      OfferAcceptedEvent.OutputTuple,
      OfferAcceptedEvent.OutputObject
    >;

    "OfferPlaced(bytes32,bytes32,address,uint256,uint256)": TypedContractEvent<
      OfferPlacedEvent.InputTuple,
      OfferPlacedEvent.OutputTuple,
      OfferPlacedEvent.OutputObject
    >;
    OfferPlaced: TypedContractEvent<
      OfferPlacedEvent.InputTuple,
      OfferPlacedEvent.OutputTuple,
      OfferPlacedEvent.OutputObject
    >;
  };
}
